bucket_name: bs-llm-sandbox
input_file_path: 'prompts_responses_finetuned.csv'
save_path: 'keenanh/dfl-eval-tests/recipe_sample_inf_edit_distance.csv'
text_save_path: 'keenanh/dfl-eval-tests/output/summary.text'
eval_method: 'edit_distance'

reference_col: 'real'
modell_response_col: 'response'
modelr_response_col: 'dfl_response'


aws_credentials: 
  aws_access_key_id: ''
  aws_secret_access_key: ''
  aws_region: ''